version: '3'

services:
  db:
    image: mongo:latest
    container_name: db
    restart: unless-stopped
    env_file: .env.development
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
